channels:
- conda-forge
dependencies:
- python=3.8.8
- pip<=25.0.1
- pip:
  - mlflow==2.17.2
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - psutil==5.9.8
  - scikit-learn==1.2.2
  - scipy==1.10.1
name: mlflow-env
